name: Checks
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm ci
        name: Install dependencies
      - run: npm run ci
        name: Build and test
      - uses: ./
        name: Run Action
        with:
          directory: 'dist'
          ecmaVersion: 'es5'
          files: '*.js'
